export const FIELDS = [
    {type: 'Text Field', value: 'textBox', viewValue: 'Text Box'},
    {type: 'Text Field', value: 'textArea', viewValue: 'Text Area'},
    {type: 'Text Field', value: 'color', viewValue: 'Color'},
    {type: 'Text Field', value: 'date', viewValue: 'Date'},
    {type: 'Text Field', value: 'email', viewValue: 'Email'},
    {type: 'Text Field', value: 'image', viewValue: 'Image'},
    {type: 'Text Field', value: 'imageUpload', viewValue: 'Image Upload'},
    {type: 'Text Field', value: 'imageAnnotator', viewValue: 'Image Annotator'},
    {type: 'Text Field', value: 'number', viewValue: 'Number'},
    {type: 'Text Field', value: 'password', viewValue: 'Password'},
    {type: 'Text Field', value: 'range', viewValue: 'Range'},
    {type: 'Text Field', value: 'time', viewValue: 'Time'},
    {type: 'Text Field', value: 'url', viewValue: 'URL'},
    {type: 'Text Field', value: 'textEditor', viewValue: 'Text Editor'},
    {type: 'Table', value: 'tabularEntry', viewValue: 'Tabular Entry'},
    {type: 'Multi-select Field', value: 'checkbox', viewValue: 'Checkbox'},
    {type: 'Multi-select Field', value: 'dropdown', viewValue: 'Dropdown'},
    {type: 'Multi-select Field', value: 'radio', viewValue: 'Radio'},
    {type: 'Display Text', value: 'customText', viewValue: 'Custom Text'},
    // {type: 'Display Text', value: 'headerText', viewValue: 'Header Text'},
    // {type: 'Display Text', value: 'footerText', viewValue: 'Footer Text'},
    {type: 'Other', value: 'formLogo', viewValue: 'Form Logo'},
];